In [32]:
# Libraries
import re
import requests
import pandas as pd

In [33]:
# Read in base files.
gtexData = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/gtexData.parquet")
emtabData = pd.read_parquet("/Users/andrewhsu/Projects/McNair/data/EMTAB6081Data.parquet")

In [89]:
gtexData

,ENSG00000290825.2,ENSG00000223972.6,ENSG00000310526.1,ENSG00000243485.6,ENSG00000237613.3,ENSG00000308361.1,ENSG00000290826.2,ENSG00000268020.3,ENSG00000186092.7,ENSG00000241860.8,...,ENSG00000210176.1,ENSG00000210184.1,ENSG00000210191.1,ENSG00000198786.2,ENSG00000198695.2,ENSG00000210194.1,ENSG00000198727.2,ENSG00000210195.2,ENSG00000210196.2,Tissue.Type
GTEX-111CU-0526-SM-5EGHK,0.000000,0.0,0.612349,0.034401,0.000000,0.0,0.000000,0.000000,0.057187,0.058056,...,1.084893,0.634386,0.527166,2439.027344,2944.897705,11.933819,8588.482422,0.000000,0.000000,Pancreas
GTEX-111YS-1226-SM-5EGGJ,0.016610,0.0,0.386135,0.000000,0.000000,0.0,0.049024,0.000000,0.023931,0.043731,...,1.362005,0.000000,0.000000,2133.339111,2734.978027,9.534033,11147.070312,0.949276,0.921356,Pancreas
GTEX-1122O-0726-SM-5GIEV,0.000000,0.0,0.935880,0.000000,0.000000,0.0,0.072210,0.000000,0.044063,0.039365,...,1.003097,0.782076,0.000000,2317.819336,3608.737549,17.052656,12645.546875,0.000000,0.339283,Pancreas
GTEX-1128S-0826-SM-5GZZI,0.000000,0.0,1.389022,0.000000,0.000000,0.0,0.087381,0.034509,0.031992,0.015156,...,0.000000,0.000000,0.000000,733.266113,569.954651,0.404610,8317.146484,0.423002,0.000000,Pancreas
GTEX-117YX-0226-SM-5EGH6,0.000000,0.0,0.686950,0.000000,0.018129,0.0,0.098904,0.039060,0.048281,0.031859,...,1.373899,0.535588,0.890132,2527.486328,3684.884033,11.907127,8695.977539,0.957566,1.394104,Pancreas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GTEX-ZVT3-1626-SM-5GU66,0.021561,0.0,1.348763,0.000000,0.000000,0.0,0.063636,0.000000,0.093193,0.028383,...,0.000000,4.135258,0.000000,7201.433594,5897.970215,10.018512,40513.937500,0.616112,1.195982,Liver
GTEX-ZVT4-0626-SM-5E45T,0.000000,0.0,1.051334,0.029331,0.054926,0.0,0.049940,0.039446,0.097515,0.039599,...,0.000000,1.081760,1.348391,5487.423340,4739.679688,6.012391,47358.128906,0.967028,0.469293,Liver
GTEX-ZYT6-0626-SM-5E45V,0.015521,0.0,0.590438,0.053810,0.016794,0.0,0.000000,0.000000,0.167719,0.027243,...,0.424241,0.496146,0.412290,3610.788086,3061.635010,4.666646,30968.281250,0.000000,0.860959,Liver
GTEX-ZYY3-0626-SM-5NQ6W,0.018798,0.0,2.367814,0.000000,0.000000,0.0,0.055483,0.087648,0.027085,0.032995,...,1.027642,0.000000,0.499347,6278.348145,5353.770996,4.110568,38080.480469,0.000000,1.564132,Liver
GTEX-ZZPU-0426-SM-5GZYH,0.000000,0.0,1.027440,0.036640,0.000000,0.0,0.124772,0.049276,0.091363,0.037101,...,0.000000,0.675672,0.561474,8072.571289,12516.819336,28.309685,19818.150391,1.208020,2.931225,Liver

In [94]:
emtabData

,Pancreas,Liver,Stomach,Duodenum,Jejunum,Ileum,Colon,Kidney,Quadriceps,Thymus,...,Duodenum,Jejunum,Ileum,Colon,Kidney,Quadriceps,Thymus,Heart,Esophagus,Brain
ENSMUSG00000000001,0.512887,5.926545,5.733410,11.268121,14.997442,18.987661,12.958968,7.782625,1.466109,18.098834,...,8.944480,13.962269,14.539717,11.311051,7.060182,1.546428,17.419960,2.094721,10.634418,3.348194
ENSMUSG00000000003,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019166,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000000028,0.010531,0.111843,0.381710,0.642235,0.692123,1.464154,1.527913,0.264255,0.275475,6.603444,...,0.699866,1.087083,1.022826,0.992046,0.143004,0.265119,6.619279,0.266752,0.473103,0.179512
ENSMUSG00000000031,0.094048,0.009826,0.112698,0.013387,0.022707,0.034533,0.013361,0.004695,58.680567,1.525592,...,0.057532,0.154973,0.118522,0.219733,0.181899,99.628396,1.877733,1.272518,157.098081,0.151693
ENSMUSG00000000037,0.000000,0.000000,0.019612,0.026431,0.008538,0.068887,0.272336,0.038901,0.017164,0.466792,...,0.021613,0.129843,0.026193,0.422155,0.037721,0.036856,0.107689,0.060564,0.223384,0.130295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ENSMUSG00000109574,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.021082,...,0.000000,0.000000,0.000000,0.006295,0.002515,0.000000,0.007032,0.000000,0.000000,0.018783
ENSMUSG00000109575,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.002722,0.000000,0.100099
ENSMUSG00000109576,0.000000,0.000000,0.000000,0.005492,0.010355,0.000000,0.000000,0.000000,0.005321,0.013416,...,0.000000,0.004363,0.000000,0.000000,0.003856,0.004398,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000109577,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000109578,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [35]:
filePath = "/Users/andrewhsu/Projects/McNair/notes/tissueSample.tsv"
with open(filePath, "w") as f:
    tissues = gtexData["Tissue.Type"].unique()
    for tissue in tissues:
        samples = gtexData[gtexData["Tissue.Type"] == tissue].index
        f.write(f"{tissue}:\n")
        for sample in samples:
            f.write(f"{sample}\n")

In [36]:
gtexData.groupby("Tissue.Type").mean()

,ENSG00000290825.2,ENSG00000223972.6,ENSG00000310526.1,ENSG00000243485.6,ENSG00000237613.3,ENSG00000308361.1,ENSG00000290826.2,ENSG00000268020.3,ENSG00000186092.7,ENSG00000241860.8,...,ENSG00000198886.2,ENSG00000210176.1,ENSG00000210184.1,ENSG00000210191.1,ENSG00000198786.2,ENSG00000198695.2,ENSG00000210194.1,ENSG00000198727.2,ENSG00000210195.2,ENSG00000210196.2
Tissue.Type,,,,,,,,,,,,,,,,,,,,,
Brain,0.015776,0.000000,1.539431,0.012059,0.018582,0.010717,0.057400,0.064114,0.105903,0.066538,...,52893.136719,1.950787,2.637299,2.611459,9671.000977,9340.288086,24.198851,32579.523438,1.501267,3.568419
Colon,0.013339,0.001203,2.967316,0.013548,0.015583,0.008395,0.048515,0.049134,0.071628,0.061812,...,39908.917969,0.626656,1.174324,0.645664,6173.651367,6831.227051,20.310787,25308.314453,0.848070,2.181220
Esophagus,0.011278,0.001370,2.608385,0.012629,0.012458,0.005970,0.036330,0.038843,0.055484,0.072906,...,35268.250000,0.526451,0.926344,0.527066,6746.267578,7601.750488,21.863308,23163.398438,0.558897,2.338656
Heart,0.016550,0.000684,0.926743,0.010169,0.020532,0.009500,0.061241,0.066180,0.124225,0.043110,...,63615.488281,1.183902,1.883346,1.415302,12510.531250,12722.797852,33.827263,42828.328125,1.184646,3.065069
Kidney,0.015814,0.000000,2.086403,0.016873,0.016712,0.011622,0.053584,0.060211,0.094974,0.050524,...,56645.085938,1.239191,2.273166,1.306157,6821.251953,6352.944336,12.393826,43361.222656,0.696391,2.640242
Liver,0.014713,0.000000,1.263502,0.010591,0.015884,0.007568,0.052284,0.053843,0.081846,0.034091,...,58823.546875,0.723724,1.395172,0.735424,6539.695312,6382.552734,14.138846,32576.052734,0.796618,1.493943
Pancreas,0.004899,0.000000,1.365353,0.007739,0.005283,0.001738,0.018965,0.017168,0.025819,0.046845,...,14501.492188,0.393548,0.738132,0.419172,1912.744019,2231.997803,7.691415,9442.833984,0.439763,0.639500
Stomach,0.014514,0.000000,2.247906,0.013823,0.013290,0.007760,0.042426,0.047717,0.072584,0.052845,...,46467.167969,0.658555,1.472624,0.742489,8642.169922,10898.611328,33.331100,28160.242188,0.923665,2.536662

In [37]:
emtabData.columns

Index(['199_1_Pancreas', '199_2_Liver', '199_3_Stomach', '199_4_Duodenum',
       '199_5_Jejunum', '199_6_Ileum', '199_7_Colon', '199_8_Kidney',
       '199_9_Quadriceps', '199_10_Thymus', '199_11_Heart', '199_12_Esophagus',
       '199_13_Brain', '199_14_Pancreas', '199_15_Liver', '199_16_Stomach',
       '199_17_Duodenum', '199_18_Jejunum', '199_19_Ileum', '199_20_Colon',
       '199_21_Kidney', '199_22_Quadriceps', '199_23_Thymus', '199_24_Heart',
       '199_25_Esophagus', '199_26_Brain', '199_27_Pancreas', '199_28_Liver',
       '199_29_Stomach', '199_30_Duodenum', '199_31_Jejunum', '199_32_Ileum',
       '199_33_Colon', '199_34_Kidney', '199_35_Quadriceps', '199_36_Thymus',
       '199_37_Heart', '199_38_Esophagus', '199_39_Brain'],
      dtype='str')

In [38]:
# Group the data by the tissue type and then average genes from the same tissue type.
gtexDataReformatted = gtexData.groupby("Tissue.Type").mean().T
gtexDataReformatted.columns.name = None
gtexDataReformatted.index.name = "Gene.ID"
gtexDataReformatted.index = [gene[:gene.find(".")] for gene in gtexDataReformatted.index]
gtexDataReformatted

,Brain,Colon,Esophagus,Heart,Kidney,Liver,Pancreas,Stomach
ENSG00000290825,0.015776,0.013339,0.011278,0.016550,0.015814,0.014713,0.004899,0.014514
ENSG00000223972,0.000000,0.001203,0.001370,0.000684,0.000000,0.000000,0.000000,0.000000
ENSG00000310526,1.539431,2.967316,2.608385,0.926743,2.086403,1.263502,1.365353,2.247906
ENSG00000243485,0.012059,0.013548,0.012629,0.010169,0.016873,0.010591,0.007739,0.013823
ENSG00000237613,0.018582,0.015583,0.012458,0.020532,0.016712,0.015884,0.005283,0.013290
...,...,...,...,...,...,...,...,...
ENSG00000198695,9340.288086,6831.227051,7601.750488,12722.797852,6352.944336,6382.552734,2231.997803,10898.611328
ENSG00000210194,24.198851,20.310787,21.863308,33.827263,12.393826,14.138846,7.691415,33.331100
ENSG00000198727,32579.523438,25308.314453,23163.398438,42828.328125,43361.222656,32576.052734,9442.833984,28160.242188
ENSG00000210195,1.501267,0.848070,0.558897,1.184646,0.696391,0.796618,0.439763,0.923665
ENSG00000210196,3.568419,2.181220,2.338656,3.065069,2.640242,1.493943,0.639500,2.536662

In [39]:
gtexDataReformatted.index.unique().to_series().to_csv("/Users/andrewhsu/Projects/McNair/notes/gtexDataGenes.csv", index=False)

In [40]:
# Reformat the name of of columns from XXX_X_Tissue to just Tissue. Then group and average columns with the same name together.
emtabData.columns = [col[re.search(r"[A-Z][a-z]", col).start():] for col in emtabData.columns]
emtabDataReformatted = emtabData.T.groupby(level=0).mean().T
emtabDataReformatted.index.name = "Gene.ID"
emtabDataReformatted = emtabDataReformatted.loc[:, list(gtexDataReformatted.columns)]
emtabDataReformatted

,Brain,Colon,Esophagus,Heart,Kidney,Liver,Pancreas,Stomach
Gene.ID,,,,,,,,
ENSMUSG00000000001,3.491125,12.918058,14.327069,7.289805,7.292047,4.574455,0.890161,5.400340
ENSMUSG00000000003,0.000000,0.000000,0.000000,0.005368,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000000028,0.223612,1.132353,0.561331,2.268044,0.228048,0.087172,0.018164,0.349117
ENSMUSG00000000031,0.256743,0.113783,265.025704,1.737279,0.075890,0.130723,0.167222,0.228744
ENSMUSG00000000037,0.122693,0.267582,0.328520,0.077485,0.033373,0.001122,0.000000,0.028755
...,...,...,...,...,...,...,...,...
ENSMUSG00000109574,0.033280,0.004708,0.002177,0.001534,0.000838,0.000000,0.000000,0.000000
ENSMUSG00000109575,0.109874,0.000000,0.000000,0.000907,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000109576,0.002251,0.000000,0.000000,0.002440,0.001285,0.000000,0.000000,0.000000
ENSMUSG00000109577,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
ENSMUSG00000109578,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [41]:
emtabDataReformatted.index.unique().to_series().to_csv("/Users/andrewhsu/Projects/McNair/notes/emtabDataGenes.csv", index=False)

In [42]:
gtexBioType = pd.read_csv("/Users/andrewhsu/Projects/McNair/data/gtexBioType.txt", sep="\t")
emtabBioType = pd.read_csv("/Users/andrewhsu/Projects/McNair/data/emtabBioType.txt", sep="\t")

In [43]:
gtexBioType

,Gene stable ID,Gene stable ID version,Transcript stable ID,Transcript stable ID version,Gene type
0,ENSG00000012817,ENSG00000012817.16,ENST00000469599,ENST00000469599.6,protein_coding
1,ENSG00000012817,ENSG00000012817.16,ENST00000317961,ENST00000317961.9,protein_coding
2,ENSG00000012817,ENSG00000012817.16,ENST00000541639,ENST00000541639.5,protein_coding
3,ENSG00000012817,ENSG00000012817.16,ENST00000382806,ENST00000382806.6,protein_coding
4,ENSG00000012817,ENSG00000012817.16,ENST00000492117,ENST00000492117.1,protein_coding
...,...,...,...,...,...
380436,ENSG00000301523,ENSG00000301523.1,ENST00000779475,ENST00000779475.1,lncRNA
380437,ENSG00000301523,ENSG00000301523.1,ENST00000779472,ENST00000779472.1,lncRNA
380438,ENSG00000301523,ENSG00000301523.1,ENST00000779473,ENST00000779473.1,lncRNA
380439,ENSG00000301523,ENSG00000301523.1,ENST00000779474,ENST00000779474.1,lncRNA
380440,ENSG00000305789,ENSG00000305789.1,ENST00000812970,ENST00000812970.1,lncRNA

In [92]:
pd.merge(gtexDataReformatted, gtexBioType.loc[:, ["Gene stable ID", "Gene type"]].drop_duplicates(), left_index=True, right_on="Gene stable ID", how="outer").set_index("Gene stable ID")

,Brain,Colon,Esophagus,Heart,Kidney,Liver,Pancreas,Stomach,Gene type
Gene stable ID,,,,,,,,,
ENSG00000000003,5.799691,22.906008,18.107586,3.414238,15.745596,23.313591,7.128223,10.594314,protein_coding
ENSG00000000005,0.169146,0.753748,0.284215,0.258039,0.956031,0.018972,0.050229,0.206583,protein_coding
ENSG00000000419,21.387617,40.514694,43.498722,24.609381,25.236029,22.603436,22.147223,37.476429,protein_coding
ENSG00000000457,2.830432,6.585192,6.015115,1.902403,3.748399,4.093346,3.044870,5.295540,protein_coding
ENSG00000000460,1.347589,2.231597,2.198975,0.689768,0.988887,1.240150,0.699461,1.596039,protein_coding
...,...,...,...,...,...,...,...,...,...
ENSG00000310553,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310554,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310555,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310556,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310557,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA

In [95]:
# Add in the biotype of genes from BioMart.
gtexDataReformattedMerged = pd.merge(gtexDataReformatted, gtexBioType.loc[:, ["Gene stable ID", "Gene type"]].drop_duplicates(), left_index=True, right_on="Gene stable ID", how="outer").set_index("Gene stable ID")
# gtexDataReformattedMerged = gtexDataReformattedMerged[gtexDataReformattedMerged["Gene type"] == "protein_coding"]
gtexDataReformattedMerged.to_parquet("/Users/andrewhsu/Projects/McNair/data/gtexExpressionProfile.parquet", index=True)
gtexDataReformattedMerged.to_csv("/Users/andrewhsu/Projects/McNair/data/gtexExpressionProfile.csv", index=True)
gtexDataReformattedMerged

,Brain,Colon,Esophagus,Heart,Kidney,Liver,Pancreas,Stomach,Gene type
Gene stable ID,,,,,,,,,
ENSG00000000003,5.799691,22.906008,18.107586,3.414238,15.745596,23.313591,7.128223,10.594314,protein_coding
ENSG00000000005,0.169146,0.753748,0.284215,0.258039,0.956031,0.018972,0.050229,0.206583,protein_coding
ENSG00000000419,21.387617,40.514694,43.498722,24.609381,25.236029,22.603436,22.147223,37.476429,protein_coding
ENSG00000000457,2.830432,6.585192,6.015115,1.902403,3.748399,4.093346,3.044870,5.295540,protein_coding
ENSG00000000460,1.347589,2.231597,2.198975,0.689768,0.988887,1.240150,0.699461,1.596039,protein_coding
...,...,...,...,...,...,...,...,...,...
ENSG00000310553,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310554,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310555,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310556,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA
ENSG00000310557,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,lncRNA

In [45]:
emtabBioType.loc[:, ["Gene stable ID", "Gene type"]]

            Gene stable ID       Gene type
0       ENSMUSG00000024304  protein_coding
1       ENSMUSG00000024304  protein_coding
2       ENSMUSG00000024304  protein_coding
3       ENSMUSG00000025075  protein_coding
4       ENSMUSG00000025075  protein_coding
...                    ...             ...
174513  ENSMUSG00000098505  protein_coding
174514  ENSMUSG00000098505  protein_coding
174515  ENSMUSG00000103532             TEC
174516  ENSMUSG00000103009             TEC
174517  ENSMUSG00000093752  protein_coding

[174518 rows x 2 columns]

In [93]:
pd.merge(emtabDataReformatted, emtabBioType.loc[:, ["Gene stable ID", "Gene type"]].drop_duplicates(), left_index=True, right_on="Gene stable ID", how="outer").set_index("Gene stable ID")

,Brain,Colon,Esophagus,Heart,Kidney,Liver,Pancreas,Stomach,Gene type
Gene stable ID,,,,,,,,,
ENSMUSG00000000001,3.491125,12.918058,14.327069,7.289805,7.292047,4.574455,0.890161,5.400340,protein_coding
ENSMUSG00000000003,0.000000,0.000000,0.000000,0.005368,0.000000,0.000000,0.000000,0.000000,protein_coding
ENSMUSG00000000028,0.223612,1.132353,0.561331,2.268044,0.228048,0.087172,0.018164,0.349117,protein_coding
ENSMUSG00000000031,0.256743,0.113783,265.025704,1.737279,0.075890,0.130723,0.167222,0.228744,lncRNA
ENSMUSG00000000037,0.122693,0.267582,0.328520,0.077485,0.033373,0.001122,0.000000,0.028755,protein_coding
...,...,...,...,...,...,...,...,...,...
ENSMUSG00000109574,0.033280,0.004708,0.002177,0.001534,0.000838,0.000000,0.000000,0.000000,TEC
ENSMUSG00000109575,0.109874,0.000000,0.000000,0.000907,0.000000,0.000000,0.000000,0.000000,TEC
ENSMUSG00000109576,0.002251,0.000000,0.000000,0.002440,0.001285,0.000000,0.000000,0.000000,TEC
ENSMUSG00000109577,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,processed_pseudogene
ENSMUSG00000109578,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN

In [96]:
# Add in the biotype of genes from BioMart.
emtabDataReformattedMerged = pd.merge(emtabDataReformatted, emtabBioType.loc[:, ["Gene stable ID", "Gene type"]].drop_duplicates(), left_index=True, right_on="Gene stable ID", how="outer").set_index("Gene stable ID")
# emtabDataReformattedMerged = emtabDataReformattedMerged[emtabDataReformattedMerged["Gene type"] == "protein_coding"]
emtabDataReformattedMerged.to_parquet("/Users/andrewhsu/Projects/McNair/data/emtabExpressionProfile.parquet", index=True)
emtabDataReformattedMerged.to_csv("/Users/andrewhsu/Projects/McNair/data/emtabExpressionProfile.csv", index=True)
emtabDataReformattedMerged

,Brain,Colon,Esophagus,Heart,Kidney,Liver,Pancreas,Stomach,Gene type
Gene stable ID,,,,,,,,,
ENSMUSG00000000001,3.491125,12.918058,14.327069,7.289805,7.292047,4.574455,0.890161,5.400340,protein_coding
ENSMUSG00000000003,0.000000,0.000000,0.000000,0.005368,0.000000,0.000000,0.000000,0.000000,protein_coding
ENSMUSG00000000028,0.223612,1.132353,0.561331,2.268044,0.228048,0.087172,0.018164,0.349117,protein_coding
ENSMUSG00000000031,0.256743,0.113783,265.025704,1.737279,0.075890,0.130723,0.167222,0.228744,lncRNA
ENSMUSG00000000037,0.122693,0.267582,0.328520,0.077485,0.033373,0.001122,0.000000,0.028755,protein_coding
...,...,...,...,...,...,...,...,...,...
ENSMUSG00000109574,0.033280,0.004708,0.002177,0.001534,0.000838,0.000000,0.000000,0.000000,TEC
ENSMUSG00000109575,0.109874,0.000000,0.000000,0.000907,0.000000,0.000000,0.000000,0.000000,TEC
ENSMUSG00000109576,0.002251,0.000000,0.000000,0.002440,0.001285,0.000000,0.000000,0.000000,TEC
ENSMUSG00000109577,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,processed_pseudogene
ENSMUSG00000109578,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN

In [87]:
gtexOriginalGenes = set(gene[:gene.find(".")] for gene in gtexData.columns[:-1])
gtexFinalGenes = set(gtexDataReformattedMerged.index)
gtexDroppedGenes = gtexOriginalGenes.difference(gtexFinalGenes)
with open("/Users/andrewhsu/Projects/McNair/notes/gtexDroppedGenesAfterGeneTypeFiltering.txt", "w") as f:
    for gene in gtexDroppedGenes:
        f.write(f"{gene}\n")

In [88]:
emtabOriginalGenes = set(emtabData.index)
emtabFinalGenes = set(emtabDataReformattedMerged.index)
emtabDroppedGenes = emtabOriginalGenes.difference(emtabFinalGenes)
with open("/Users/andrewhsu/Projects/McNair/notes/emtabDroppedGenesAfterGeneTypeFiltering.txt", "w") as f:
    for gene in emtabDroppedGenes:
        f.write(f"{gene}\n")